### ISSUE TITLE
Tipagem estática da camada de serviço

### ISSUE THREAD

**Issue by rafaelcanovas** [ale-jr/animavita#1]
https://github.com/ale-jr/animavita/blob/f4c67199bda7269c5b4e4b9f9c6e2740be315221/src/services/characterService/index.js#L1-L30

Boa tarde Alê, tudo bem?

Na sua opinião, quais seriam os ganhos e perdas ao implementarmos funcionalidades de tipagem estática (utilizando TypeScript), na camada de serviço da aplicação?

**Comment by ale-jr** [comment]
Ganhos: 
- Maior confiabilidade para o resto da aplicação
- Menos tempo perdido tentando lembrar a estrutura ou vendo a doc
Perdas: 
- O desenvolvimento de cada camada demora um pouco mais

**Comment by rafaelcanovas** [comment]
Obrigado Alê!
