### ISSUE TITLE
Escolha do Atomic Design

### ISSUE THREAD

**Issue by rafaelcanovas** [ale-jr/animavita#2]
Boa tarde Alê, tudo bem?

Se importaria de elaborar um pouco sobre a escolha que fez pelo Atomic Design para o desenvolvimento desta aplicação? E como isso beneficia uma aplicação tão pequena quanto esta?

Abs.

**Comment by ale-jr** [comment]
Para ser bem sincero, para um projeto pequeno não faz tanto sentido pois a divisão fica mais complexa, porém a minha ideia é que ter um padrão, mesmo que não seja perfeito para a aplicação, é melhor do que não seguir nenhum e só jogar os componentes de ui em uma pasta de componentes. O Atomic foi o primeiro que eu pensei pq é o que eu uso no dia a dia, mas se eu estivesse começando um projeto do zero eu iria levantar todos os pontos positivos e negativos de cada abordagem 😄
Atomic é legal para quando o time de design participa junto, assim os componentes ficam muito mais reutilizáveis, porém distribuir geralmente aumenta complexidade o que significa que nem sempre Atomic vai ser a melhor opção

**Comment by rafaelcanovas** [comment]
Obrigado Alê!
