### ISSUE TITLE
Garantia da assinatura da resposta da API

### ISSUE THREAD

**Issue by rafaelcanovas** [ale-jr/animavita#3]
https://github.com/ale-jr/animavita/blob/f4c67199bda7269c5b4e4b9f9c6e2740be315221/src/hooks/useCharacterSearch/useCharacterSearch.spec.js#L11-L104

Boa tarde Alê, tudo bem?

É muito comum utilizar um Mock da resposta da API, mas isso de nada vale se o formato realmente retornado pela API for alterado, os testes passarão mas a aplicação irá finalmente falhar na integração. Como você, diariamente faz, para diminuir as chances de falha de integração da aplicação com a API?

Abs.

**Comment by ale-jr** [comment]
Desculpa pela demora, a notificação por email do github foi direto para o spam :sweat_smile: 

Como eu não conheço a API eu achei melhor fazer um mock para garantir uma fonte de dados consistente para os testes, porém sei que isso vai afetar muito a confiabilidade. Se eu tivesse mais acesso a API, eu subiria um ambiente do backend com uma seed específica só para esses testes, assim eu consigo testar se o contrato está sendo seguido. Se não tivesse acesso a API eu conversaria com o time para chegar em outra opção, talvez tirar o mock e/ou mais alguns testes para garantir que o contrato.

**Comment by rafaelcanovas** [comment]
Hehehe tranquilo!

Obrigado Alê.

Abs.
